### ISSUE TITLE
AMI to clone & run repository

### ISSUE THREAD

**Issue by ereday** [YerevaNN/translit-rnn#10]
Hi,
Is there any  AMI publicly available on Amazon  so that we can run the model on it without need to install all required packages and other stuff ? 

If this is not possible, could you provide step-wise instructions to run the model (with requirements.txt file). 
I want to do 2 things: 
1 ) Run the pre-trained models on armenian language but I don't know how to do that right now.
2) Train a model from scratch with the same dataset you described in the blog post. 

Thanks.

**Comment by TigranGalstyan** [comment]
Hi @ereday 
Unfortunately there is no AMI available now.
I'm not sure about availability of the pretrained model, but I can provide one if necessary.
I've created requirements.txt file in the repo.
The step by step instructions to reproduce the training are given in the bottom of readme file, [here](https://github.com/yerevann/translit-rnn#preparing-the-data-for-a-given-language).

Thanks for your interest in the work.

**Comment by ereday** [comment]
Thanks for reply. A pretrained model would be amazing if possible. Should I keep this issue open until getting the model ?

**Comment by TigranGalstyan** [comment]
I've attached our pretrained model here.
Looking forward to hearing from you.
[init_ortho.hdim228.depth1.seq_len100.bs50.epoch21.loss0.0078.npy.zip](https://github.com/YerevaNN/translit-rnn/files/1361909/init_ortho.hdim228.depth1.seq_len100.bs50.epoch21.loss0.0078.npy.zip)
