### ISSUE TITLE
Separation of Eastern and Western Armenians

### ISSUE THREAD

**Issue by otanim** [YerevaNN/translit-rnn#7]
As you know, we have codes for the representation of name of Armenian language:
- ISO 639-2 (bibliographic): &nbsp; &nbsp;**arm**
- ISO 639-2 (terminology):&nbsp; &nbsp; &nbsp;**hye**
- ISO 639-1: &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;**hy**
- RFC 4646: &nbsp;&nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;**hy-AM**

But unfortunately seems we don't have any ISO standard identification code to separate **W**estern Armenian from **E**astern Armenian.

Currently you have generated db of eastern Armenian. Do you guys think it's relevant to separate (or add)  western version of Armenian language?  

---------------------------  

**Similar projects**:
- @barseghyanartur / [transliterate](https://github.com/barseghyanartur/transliterate)
- @gcardone / [junidecode](https://github.com/gcardone/junidecode)  

**Useful links**:
- [ALA-LC Romanization Tables](https://www.loc.gov/catdir/cpso/roman.html)
- [Codes for the Representation of Names of Languages](https://www.loc.gov/standards/iso639-2/php/code_list.php)
- [SDL Media Manager: Language Codes](http://docs.sdl.com/LiveContent/content/en-US/SDL_MediaManager_241/concept_A9F20DF9433C46FF8FED8FA11A29FAA0)

**Comment by Hrant-Khachatrian** [comment]
Well, the content we use comes from hy.wikipedia, which is not only Eastern Armenian (e.g. [Հայաստան](https://hy.wikipedia.org/wiki/%D5%80%D5%A1%D5%B5%D5%A1%D5%BD%D5%BF%D5%A1%D5%B6_(%D5%A1%D6%80%D5%A5%D6%82%D5%B4%D5%BF%D5%A1%D5%B0%D5%A1%D5%B5%D5%A5%D6%80%D5%A7%D5%B6)))

ideally we could identify whether it's Eastern or Western and have even different versions of Armenian->Latin mapping, but that's beyond the scope of this work for now.

**Comment by otanim** [comment]
@Hrant-Khachatrian understood, thanks!
